### PR TITLE
Fedora docs

### PR DESCRIPTION
**Pull request by plaes**
Added some Fedora-specific notes on getting started

### CODE REVIEW

**Comment by japaric** [comment]
I'm a bit afraid that adding docs for a second Linux distro will open the door to receiving PRs for even more distros.

My preference here would be document a single distribution (preferably the one we use in CI because it's what we test) and say that this provided as a reference and that you should consult your package manager to see what are the equivalent packages.

**Comment by japaric** [comment]
> single distribution

And by "single distribution" I also meant a single release like Ubuntu 14.04 -- that should be specified in the docs. Otherwise we will have to add notes about some packages not being supported in recent releases. For example, see rust-embedded/discovery#91

**Comment by therealprof** [comment]
I agree with @japaric here.

**Comment by adamgreig** [comment]
> I'm a bit afraid that adding docs for a second Linux distro will open the door to receiving PRs for even more distros.

For the quickstart crate in particular, would that be such a bad thing? The users reading this are likely the ones needing the most help getting started. Telling users "figure out how to installer a debugger yourself if you're not using Ubuntu 14.04" isn't especially helpful for them.

We could at least point people to the [official ARM gcc distribution](https://developer.arm.com/open-source/gnu-toolchain/gnu-rm), which has installation instructions and static binaries for everyone, and includes arm-none-eabi-gdb as well.

**Comment by korken89** [comment]
I would agree with @adamgreig, let's push them the right direction at least

**Comment by Disasm** [comment]
Looks like these changes are a bit outdated. Relevant instructions for Fedora are given in the [embedded Rust book](https://rust-embedded.github.io/book/intro/install/linux.html).
Thank you for your help! Feel free to open PR in the [book repo](https://github.com/rust-embedded/book) if you have some updates.

**Pull request closed without merging**
