### PR TITLE
Update quickstart tutorial instructions.

### PR DESCRIPTION
**Pull request by akovacs**
1. Add udev rule to access USB ST-LINK from OpenOCD as non-root user.
2. Add runnable OpenOCD launch command for STM32F3-Discovery board.
3. Add cargo-edit as a required dependency since the instructions include the
   `cargo add` subcommand.

### CODE REVIEW

**Comment by Emilgardis** [comment]
`cargo-edit` is not a required dependency, I would much better have the code block where it is used to be annotated with
> `cargo add` comes from the `cargo-edit` binary, you can install it with `cargo install cargo-edit`

**Comment by akovacs** [comment]
I've removed `cargo-edit` as a required dependency and added a comment clarifying that `cargo-edit` provides the `cargo add` subcommand.

**Comment by mathk** [comment]
Ping from triage: This change seems quite outdated. @rust-embedded/cortex-m. Can we confirm that?

**Comment by korken89** [comment]
This is indeed outdated, lets close this for now.

@akovacs, if you see something you want to fix again, please open another PR.
I'm very sorry for the delay in handling this PR.

**Pull request closed without merging**
