### PR TITLE
force rebuild if memory.x changed

### PR DESCRIPTION
**Pull request by obraunsdorf**

### CODE REVIEW

**Comment by adamgreig** [comment]
By default the linker will search the crate's directory without needing to be told, so having `memory.x` in the same place as `Cargo.toml` works fine; adding a build.rs which only adds `cargo:rerun-if-changed=memory.x` is enough to rerun the build when `memory.x` changes in that case. Whether we want/should (re)include that longer `build.rs` example in the quickstart, I don't know... the only edge case where it can be required is in workspaces or weird build configurations.

**Comment by therealprof** [comment]
I'm not sure where the more elaborate build.rs is coming from. Also I don't see too much value in a `build.rs` in general but if we have one it should probably provide the full benefit and not just half. Are there any downsides to providing the full version?

**Comment by thalesfragoso** [comment]
> I'm not sure where the more elaborate build.rs is coming from. Also I don't see too much value in a `build.rs` in general but if we have one it should probably provide the full benefit and not just half. Are there any downsides to providing the full version?

I always use the complex one, but some people did some testing and it seems that the cargo directory is already in the linker search path, so it's unnecessary to copy somewhere else.

**Comment by therealprof** [comment]
As discussed in the meeting we should add a comment to explain when and why this might be necessary to give users a good base for a decision whether this is necessary.

**Comment by therealprof** [comment]
Addressed by #92.

**Pull request closed without merging**
