### PR TITLE
v0.3.3

### PR DESCRIPTION
**Pull request by japaric**
changes required to publish a new version

r? @adamgreig (chosen at random)

### CODE REVIEW

**Comment by japaric** [comment]
@rust-embedded/cortex-m could any of you land this and then publish a new version to crates.io? Want to confirm that the crates.io permissions are working.

**Comment by adamgreig** [comment]
https://crates.io/crates/cortex-m-quickstart :+1:

**Comment by japaric** [comment]
@adamgreig awesome! Thanks for checking

**Pull request merged**
